// Renders the sign-in page for one language.
//
// Deliberately NOT a VitePress page: it must be readable without a session, and
// the site's /assets/ bundles carry every page's content, so the page is
// self-contained (inline styles, one small script) and only leans on the logo,
// which the edge gate lets through. It POSTs to /api/login and works without
// JavaScript; the script only carries ?to through and shows the error message
// after a failed attempt. `scripts/build-login-pages.mjs` writes the files at
// build time, so they are never checked in and never drift from the config.

import { loginPath, resolveConfig, startPath } from "./config.mjs";

const TEXTS = {
    de: {
        title: "Anmelden",
        hint: "Die Zugangsdaten bekommst du von deiner Trainerin oder deinem Trainer.",
        error: "Anmeldung fehlgeschlagen. Bitte prüfe Benutzername und Passwort.",
        user: "Benutzername",
        password: "Passwort",
        submit: "Anmelden",
        switchTo: "Deutsch",
    },
    en: {
        title: "Sign in",
        hint: "You get the credentials from your trainer.",
        error: "Sign-in failed. Please check your username and password.",
        user: "Username",
        password: "Password",
        submit: "Sign in",
        switchTo: "English",
    },
};

const STYLE = `<style>
  @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&display=swap');
  :root {
    --blue: #335DE4;
    --blue-hover: #4A70E8;
    --navy: #1B1E3A;
    --fg-muted: #5A6178;
    --border: #E4E7F0;
    --bg-soft: #F7F8FB;
    --card: #FFFFFF;
    --error-bg: #FDECEC;
    --error-fg: #B3261E;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --navy: #F4F6FE;
      --fg-muted: #A7AFCD;
      --border: #252555;
      --bg-soft: #0F0F28;
      --card: #16163A;
      --error-bg: #3A1B22;
      --error-fg: #FFB4AB;
    }
  }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    min-height: 100vh;
    display: grid;
    place-items: center;
    padding: 24px;
    font-family: 'Manrope', -apple-system, 'Segoe UI', sans-serif;
    background: var(--bg-soft);
    color: var(--navy);
  }
  main {
    width: 100%;
    max-width: 400px;
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 16px;
    padding: 40px 36px 36px;
    box-shadow: 0 12px 40px rgba(27, 30, 58, 0.08);
  }
  .brand {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 28px;
  }
  .brand img { height: 18px; }
  .brand span {
    font-size: 13px;
    font-weight: 700;
    letter-spacing: 0.05em;
    text-transform: uppercase;
    color: var(--fg-muted);
  }
  h1 { font-size: 24px; font-weight: 800; margin: 0 0 6px; }
  .hint { font-size: 14px; color: var(--fg-muted); margin: 0 0 24px; line-height: 1.5; }
  label { display: block; font-size: 13px; font-weight: 600; margin: 0 0 6px; }
  input {
    width: 100%;
    font: inherit;
    font-size: 15px;
    color: inherit;
    background: transparent;
    border: 1px solid var(--border);
    border-radius: 10px;
    padding: 11px 14px;
    margin-bottom: 18px;
  }
  input:focus {
    outline: none;
    border-color: var(--blue);
    box-shadow: 0 0 0 3px rgba(51, 93, 228, 0.18);
  }
  button {
    width: 100%;
    font: inherit;
    font-size: 15px;
    font-weight: 700;
    color: #fff;
    background: var(--blue);
    border: none;
    border-radius: 10px;
    padding: 12px;
    cursor: pointer;
  }
  button:hover { background: var(--blue-hover); }
  .error {
    display: none;
    font-size: 14px;
    line-height: 1.5;
    color: var(--error-fg);
    background: var(--error-bg);
    border-radius: 10px;
    padding: 12px 14px;
    margin: 0 0 20px;
  }
  .error.show { display: block; }
  .lang { margin-top: 24px; text-align: center; font-size: 13px; }
  .lang a { color: var(--blue); text-decoration: none; }
  .lang a:hover { text-decoration: underline; }
</style>`;

const escapeHtml = (s) => String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]);

/** The sign-in page HTML for `lang` (the root language or the other one). */
export function renderLoginPage(rawConfig, lang, { logo = "/komet.svg" } = {}) {
    const config = resolveConfig(rawConfig);
    const t = TEXTS[lang];
    if (!t) throw new Error(`No sign-in texts for language ${JSON.stringify(lang)}`);
    const twin = lang === config.locale ? config.other : config.locale;
    const twinLogin = loginPath(config, twin);
    const title = escapeHtml(config.title);

    return `<!doctype html>
<!-- Generated by scripts/build-login-pages.mjs from hub.config.mjs. Do not edit. -->
<html lang="${lang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>${t.title} – ${title}</title>
${STYLE}
</head>
<body>
<main>
  <div class="brand">
    <img src="${escapeHtml(logo)}" alt="">
    <span>${title}</span>
  </div>
  <h1>${t.title}</h1>
  <p class="hint">${t.hint}</p>
  <p class="error" id="error">${t.error}</p>
  <form method="post" action="/api/login">
    <input type="hidden" name="to" id="to" value="${startPath(config, lang)}">
    <input type="hidden" name="lang" value="${lang}">
    <label for="user">${t.user}</label>
    <input id="user" name="user" autocomplete="username" autocapitalize="none" autofocus required>
    <label for="password">${t.password}</label>
    <input id="password" name="password" type="password" autocomplete="current-password" required>
    <button type="submit">${t.submit}</button>
  </form>
  <p class="lang"><a id="lang-switch" href="${twinLogin}">${TEXTS[twin].switchTo}</a></p>
</main>
<script>
  // Carry the originally requested page through the form, keep it across a
  // failed attempt, and mirror it onto the language switch. Only same-site
  // paths: the function checks again, this is just the client half.
  var params = new URLSearchParams(location.search);
  var to = params.get("to") || "";
  var sameSite = false;
  try { sameSite = to.charAt(0) === "/" && new URL(to, "https://x.invalid").origin === "https://x.invalid"; } catch (e) {}
  if (sameSite) {
    document.getElementById("to").value = to;
    document.getElementById("lang-switch").href = "${twinLogin}?to=" + encodeURIComponent(to);
  }
  if (params.get("error")) document.getElementById("error").classList.add("show");
</script>
</body>
</html>
`;
}
